etc/check-lts.sh: bootstrap pantry db with fresh download
We lost the GH workflow cache earlier this year during some downtime
and it has failed to regenerate the pantry db for weeks/months.
So this should help get up and running again.

The current error being hit looks like:

Processed 189600 cabal files
Processed 190000 cabal files
Processed 190400 cabal files
Package index cache populated
Reusing local file /home/runner/work/lts-haskell/lts-haskell/build-constraints/lts-24-build-constraints.yaml
Writing constraints.yaml
Writing snapshot-incomplete.yaml
Writing snapshot.yaml
curator: HttpExceptionRequest Request {
  host                 = "hackage.haskell.org"
  port                 = 443
  secure               = True
  requestHeaders       = [("User-Agent","Haskell pantry package")]
  path                 = "/package/fingertree-0.1.6.1.tar.gz"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
  proxySecureMode      = ProxySecureWithConnect
}
 InvalidChunkHeaders
Error: Process completed with exit code 1.