disable learn-physics (walck/learn-physics#3) and LPFP
```
       /home/curators/work/unpack-dir/unpacked/learn-physics-0.6.6-76e78fa06be2a1843b54cfee925fc08e04d67114cba194581cdaac99025ea21d/
src/Physics/Learn/Visual/VisTools.hs:105:27: error: [GHC-83865]
           • Couldn't match expected type: Vis.VisObject.Euler Double
                         with actual type: Euler Double
             NB: ‘Vis.VisObject.Euler’
                   is defined in ‘Vis.VisObject’ in package ‘Vis-0.7.7.1’
                 ‘Euler’ is defined in ‘Types’ in package ‘SpatialMath-0.2.7.1’
           • In the first argument of ‘RotEulerRad’, namely
               ‘(Euler 0 alpha 0)’
             In the expression: RotEulerRad (Euler 0 alpha 0)
             In an equation for ‘rotY’:
                 rotY alpha = RotEulerRad (Euler 0 alpha 0)
           |
       105 | rotY alpha = RotEulerRad (Euler 0 alpha 0)
           |                           ^^^^^^^^^^^^^^^

       /home/curators/work/unpack-dir/unpacked/learn-physics-0.6.6-76e78fa06be2a1843b54cfee925fc08e04d67114cba194581cdaac99025ea21d/
src/Physics/Learn/Visual/VisTools.hs:110:27: error: [GHC-83865]
           • Couldn't match expected type: Vis.VisObject.Euler Double
                         with actual type: Euler Double
             NB: ‘Vis.VisObject.Euler’
                   is defined in ‘Vis.VisObject’ in package ‘Vis-0.7.7.1’
                 ‘Euler’ is defined in ‘Types’ in package ‘SpatialMath-0.2.7.1’
           • In the first argument of ‘RotEulerRad’, namely
               ‘(Euler alpha 0 0)’
             In the expression: RotEulerRad (Euler alpha 0 0)
             In an equation for ‘rotZ’:
                 rotZ alpha = RotEulerRad (Euler alpha 0 0)
           |
       110 | rotZ alpha = RotEulerRad (Euler alpha 0 0)
           |                           ^^^^^^^^^^^^^^^
```

```
       /home/curators/work/unpack-dir/unpacked/LPFP-1.1.3-26ee40c9e603ecd7bdae6a955d1fe6c36ab6131f47ba6b292d4d38089ad9a5cf/src/LPFP/
Mechanics3D.hs:234:30: error: [GHC-83865]
           • Couldn't match expected type: Vis.VisObject.Euler R
                         with actual type: Euler a1
             NB: ‘Vis.VisObject.Euler’
                   is defined in ‘Vis.VisObject’ in package ‘Vis-0.7.7.1’
                 ‘Euler’ is defined in ‘Types’ in package ‘SpatialMath-0.2.7.1’
           • In the first argument of ‘V.RotEulerDeg’, namely
               ‘(Euler 270 180 0)’
             In the first argument of ‘($)’, namely
               ‘V.RotEulerDeg (Euler 270 180 0)’
             In the expression: V.RotEulerDeg (Euler 270 180 0) $ pict
           |
       234 | orient pict = V.RotEulerDeg (Euler 270 180 0) $ pict
           |                              ^^^^^^^^^^^^^^^

       /home/curators/work/unpack-dir/unpacked/LPFP-1.1.3-26ee40c9e603ecd7bdae6a955d1fe6c36ab6131f47ba6b292d4d38089ad9a5cf/src/LPFP/
Mechanics3D.hs:424:23: error: [GHC-83865]
           • Couldn't match expected type: Vis.VisObject.Euler R
                         with actual type: Euler a0
             NB: ‘Vis.VisObject.Euler’                                                                                                                 is defined in ‘Vis.VisObject’ in package ‘Vis-0.7.7.1’
                 ‘Euler’ is defined in ‘Types’ in package ‘SpatialMath-0.2.7.1’
           • In the first argument of ‘V.RotEulerDeg’, namely
               ‘(Euler 90 0 90)’
             In the expression: V.RotEulerDeg (Euler 90 0 90)
             In an equation for ‘zOut’: zOut = V.RotEulerDeg (Euler 90 0 90)
           |
       424 | zOut = V.RotEulerDeg (Euler 90 0 90)
           |                       ^^^^^^^^^^^^^
```